name: walletconnect_flutter_dapp
description: A dApp showing how to use WalletConnect v2 with Flutter

publish_to: "none"

version: 3.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  web3modal_flutter:
    path: ../
  walletconnect_flutter_v2: ^2.1.8
  cupertino_icons: ^1.0.2
  get_it: ^7.6.0
  logger: ^2.0.2+1
  fl_toast: ^3.1.0
  smooth_page_indicator: ^1.1.0
  web3dart: ^2.6.1
  universal_io: ^2.2.2
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  assets:
    - assets/abis/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/AppIcon.png"
